#!/bin/bash
# Build Script - Compile Each Contract Individually
# Generated by Immunefi Instascope

set -e

echo "Building 7 contracts individually..."
echo ""

echo "Building CustomToken (contract_CustomToken_5965)"
FOUNDRY_PROFILE=contract_CustomToken_5965 forge build || {
  echo "❌ Failed to build CustomToken"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_CustomToken_5965 forge build"
}
echo "✅ Built CustomToken"
echo ""

echo "Building Depositor (contract_Depositor_cb74)"
FOUNDRY_PROFILE=contract_Depositor_cb74 forge build || {
  echo "❌ Failed to build Depositor"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_Depositor_cb74 forge build"
}
echo "✅ Built Depositor"
echo ""

echo "Building Withdrawal (contract_Withdrawal_bb2f)"
FOUNDRY_PROFILE=contract_Withdrawal_bb2f forge build || {
  echo "❌ Failed to build Withdrawal"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_Withdrawal_bb2f forge build"
}
echo "✅ Built Withdrawal"
echo ""

echo "Building ERC1967Proxy (contract_ERC1967Proxy_c360)"
FOUNDRY_PROFILE=contract_ERC1967Proxy_c360 forge build || {
  echo "❌ Failed to build ERC1967Proxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ERC1967Proxy_c360 forge build"
}
echo "✅ Built ERC1967Proxy"
echo ""

echo "Building ERC1967Proxy (contract_ERC1967Proxy_50ae)"
FOUNDRY_PROFILE=contract_ERC1967Proxy_50ae forge build || {
  echo "❌ Failed to build ERC1967Proxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ERC1967Proxy_50ae forge build"
}
echo "✅ Built ERC1967Proxy"
echo ""

echo "Building NuvaVault (contract_NuvaVault_f971)"
FOUNDRY_PROFILE=contract_NuvaVault_f971 forge build || {
  echo "❌ Failed to build NuvaVault"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_NuvaVault_f971 forge build"
}
echo "✅ Built NuvaVault"
echo ""

echo "Building DedicatedVaultRouter (contract_DedicatedVaultRouter_c189)"
FOUNDRY_PROFILE=contract_DedicatedVaultRouter_c189 forge build || {
  echo "❌ Failed to build DedicatedVaultRouter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_DedicatedVaultRouter_c189 forge build"
}
echo "✅ Built DedicatedVaultRouter"
echo ""

echo "================================"
echo "Build complete - each contract compiled independently"
echo "================================"
